name: Docstrings Coverage

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

# for GITHUB_TOKEN
permissions: write-all

jobs:
  docstr_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Interrogate
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install interrogate
        pip install anybadge
    - name: Test docstr_coverage with interrogate
      run: |
        pytest test/test_docstr_coverage.py -s
    - name: Upload badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: DocstringCoverage
        path: docstr_badge.svg
    - name: Download badge as artifact
      uses: actions/download-artifact@v2
      with:
        name: DocstringCoverage
        path: docstr_badge.svg
